VinylStore/VinylStore/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace VinylStore.Models
{
    public class Artist
    {
        public int ArtistId { get; set; }
        public string ArtistName { get; set; }
        public string ImgUrl { get; set; }
        public string Description { get; set; }
        public List<Album> Albums { get; set; }


    }
}

VinylStore/VinylStore/ViewModels/ArtistViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VinylStore.Models;

namespace VinylStore.ViewModels
{
    public class ArtistViewModel
    {
       public Artist AllArtists { get; set; }



        public IEnumerable<Album> AllAlbums { get; set; }


    }
}

VinylStore/VinylStore/Controllers/ArtistController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VinylStore.Models;
using VinylStore.Models.Interface;
using VinylStore.ViewModels;

namespace VinylStore.Controllers
{
    public class ArtistController:Controller
    {
        private readonly IArtistRepository artistRepository;
        private readonly IAlbumRepository albumRepository;




        public ArtistController(IArtistRepository artistRepository, IAlbumRepository albumRepository)
        {
            this.artistRepository = artistRepository;
            this.albumRepository = albumRepository;
        }


        public IActionResult Index()
        {
            return View(artistRepository.AllArtists);
        }

        public IActionResult Details(int id)
        {
            IEnumerable<Album> albums;

            var artist = artistRepository.GetArtistById(id);   //vinylRepository.GetVinylById(id);


            //var album = albumRepository.AllAlbums.FirstOrDefault(a => a.AlbumId == id); // it's work 


            albums = albumRepository.AllAlbums.Where(a => a.ArtistId == id);

            if (artist == null)
            {
                return NotFound();
            }

            return View(new ArtistViewModel { AllArtists = artist, AllAlbums = albums});
        }


    }
}

VinylStore/VinylStore/Views/Artist/Details.cshtml
@model ArtistViewModel

<br />
<div class="thumbnail">
    <img alt="@Model.AllArtists.ArtistName" src="@Model.AllArtists.ImgUrl">
    <div class="caption-full">

        <span class="border">

            <h4>@Model.AllArtists.Description</h4>

        </span>


        @* Перечень альбомов для у каждого артиста *@


    </div>
</div>

<div class="row">

    @foreach (var album in Model.AllAlbums)
    {
    <div class="col-lg-4 col-md-6 mb-4">

        <div class="thumbnail">

            <div class="gallery2">

                <div class="ramka"> <img src="@album.ImgUrl" /> </div>

            </div>

            <div class="caption">

                <h3>
                    <a > @album.AlbumName</a>
                </h3>


              



            </div>




   




        </div>
            </div>
     }
        </div>

VinylStore/VinylStore/Views/Artist/Index.cshtml
@model IEnumerable<Artist>

<br />
    <div class="row">

        @foreach (var item in Model)
        {

            <div class="col-lg-4 col-md-6 mb-4">


                <div class="thumbnail">

                    <div class="gallery2">

                    <div class="ramka"> <img src="@item.ImgUrl"/> </div>

                    </div>

                    <div class="caption">
                        @*<h3 class="pull-right">@item.ArtistName</h3>*@
                        <h3>
                            <a asp-controller="Artist" asp-action="Details" asp-route-id="@item.ArtistId">@item.ArtistName</a>
                        </h3>

                        @*<p>@item.Description</p>*@
                    </div>

                    @*<div>
                        @Model.Album.Artist.ArtistName

                    </div>*@

                    @*<div class="addToCart">
                        <p class="button">
                            <a class="btn btn-primary"
                               asp-controller="ShoppingCart"
                               asp-action="AddToShoppingCart"
                               asp-route-vinylId="@Model.VinylId">Add to cart</a>
                        </p>
                    </div>*@


                </div>


            </div>

        }



    </div>